# fly.toml app configuration file generated for brikbin on 2024-11-23T16:09:58-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'brikbin'
primary_region = 'iad'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.2'

[env]
  APP_ENV = 'production'
  APP_URL = "https://brikbin.fly.dev"
  DB_CONNECTION = 'pgsql'
  DB_HOST = 'ep-proud-snowflake-a4m7nws6.us-east-1.aws.neon.tech'
  DB_PORT = 5432
  DB_DATABASE = 'neondb'
  DB_USERNAME = 'neondb_owner'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'
  TRUST_PROXIES = '*'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
    app = ""
    worker = "php artisan queue:listen"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
